apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: memoryleaker-deployment
spec:
  selector:
    matchLabels:
      app: memoryleaker
  replicas: 1
  template:
    metadata:
      labels:
        app: memoryleaker
    spec:
      containers:
      - name: memoryleaker
        image: quay.io/kiran01bm/openjdk:memoryleaker
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "128m"
          limits:
            memory: "256Mi"
            cpu: "150m"
        imagePullPolicy: IfNotPresent
