apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: memoryleakerunbounded-deployment
spec:
  selector:
    matchLabels:
      app: memoryleakerunbounded
  replicas: 1
  template:
    metadata:
      labels:
        app: memoryleakerunbounded
    spec:
      containers:
      - name: memoryleakerunbounded
        image: springboot/memoryleaker:latest
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
