apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-db-policy
spec:
  # Assigning Ingress policy to the DB service
  podSelector:
    matchLabels:
      role: dbPods
  # Ingress rule - 
  # 1. Allows pods in current namespace with role label "role: willTalkToDB" to talk to DB.
  # 2. Allows all pods running in any namespace with role label "role: allPodsTalkToDB" to talk to DB.
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          role: allPodsTalkToDB
    - podSelector:
        matchLabels:
          role: willTalkToDB
