apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: cpuloadgen-unbounded-deployment
spec:
  selector:
    matchLabels:
      app: cpuloadgen-unbounded
  replicas: 1
  template:
    metadata:
      labels:
        app: cpuloadgen-unbounded
    spec:
      containers:
      - name: cpuloadgen-unbounded
        image: quay.io/kiran01bm/openjdk:cpuloadgen
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
